FROM alpine:3.23
RUN addgroup -g 1000 -S mcp && adduser -u 1000 -S mcp -G mcp
ARG TARGETPLATFORM
COPY --chown=mcp:mcp $TARGETPLATFORM/mcp-victorialogs /usr/local/bin/mcp-victorialogs
RUN chmod +x /usr/local/bin/mcp-victorialogs
USER mcp
WORKDIR /home/mcp
ENTRYPOINT [ "/usr/local/bin/mcp-victorialogs" ]
